<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<BaseOutputPath></BaseOutputPath>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="ExcelNumberFormat" Version="1.1.0" />
	  <PackageReference Include="log4net" Version="3.0.3" />
	  <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="9.0.0" />
	  <PackageReference Include="ReactiveProperty" Version="9.6.0" />
	  <PackageReference Include="SixLabors.Fonts" Version="2.0.6" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="SalaryManager.config">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
