<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<BaseOutputPath></BaseOutputPath>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Aspose.PDF" Version="24.11.0" />
	  <PackageReference Include="ClosedXML" Version="0.104.2" />
	  <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
	  <PackageReference Include="Google.Apis.Calendar.v3" Version="1.68.0.3592" />
	  <PackageReference Include="Google.Apis.Sheets.v4" Version="1.68.0.3568" />
	  <PackageReference Include="SixLabors.Fonts" Version="2.0.6" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
	  <PackageReference Include="SQLite" Version="3.13.0" />
	  <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
	  <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
	  <PackageReference Include="System.Runtime.WindowsRuntime.UI.Xaml" Version="4.7.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\SalaryManager.Domain\SalaryManager.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>
</Project>
